/**
 * 문항 48개 (contentVersion 4.0.0 — 2026-08-21 확장, DEC-048)
 *
 * 검수안: docs/content/teacher-style-v1-revision.md
 *
 * 배분 규칙 (docs/content/teacher-style-v1.md 5.1)
 *   - 축 4개 × 12문항
 *   - 축마다 polarity +1 여섯 개 / -1 여섯 개 (묵종 편향 상쇄)
 *   - Part마다 네 축이 모두 섞이도록 배치
 *   - 같은 뜻을 뒤집은 짝 문항은 서로 다른 Part에 둠 (바로 옆에 있으면 답이 오염됨)
 *
 * 작성 규칙 (같은 문서 5.2 · realContent.test.ts가 자동 검사)
 *   - 축마다 전용 장면군을 쓴다 — 같은 장면이 두 축에 나오지 않게 해 겹침을 원천 차단
 *   - 교실·학교 상황을 구체적으로, 한 문항에 한 가지만
 *   - 부정문을 쓰지 않고 polarity로 방향을 뒤집음
 *   - 40자 내외, "항상 / 절대" 같은 극단 표현 없음
 *   - 빈도가 아니라 성향을 물음 ("~하는 편이다")
 *   - 반박하기 어려운 문장을 쓰지 않는다 — 모두가 동의하면 사람을 구분하지 못함
 *
 * context는 이 문항이 묻는 장면입니다 (DEC-048). 장면 안에서도 찬반이 한쪽으로
 * 몰리지 않아야 합니다 — 몰리면 응답 습관이 장면 차이로 둔갑합니다.
 *
 * id는 축 이름 + 번호입니다. 문항 순서를 바꿔도 id는 그대로 두세요.
 * (id가 바뀌면 이미 저장된 응답을 못 찾습니다)
 */
export const questions = [
  // ── Part 1 ──────────────────────────────────────────────────────────────
  {
    id: "energy-01",
    sectionId: "part-1",
    order: 1,
    text: "쉬는 시간에 옆 반 선생님과 이야기를 나누고 나면 다시 힘이 나는 편이다.",
    axisId: "axis-energy",
    polarity: 1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "lens-02",
    sectionId: "part-1",
    order: 2,
    text: "단원을 볼 때 이 내용이 아이들의 삶과 어떻게 이어질지 먼저 떠올리는 편이다.",
    axisId: "axis-lens",
    polarity: -1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "decision-01",
    sectionId: "part-1",
    order: 3,
    text: "다툼을 중재할 때 누가 어떤 행동을 했는지부터 정리하는 편이다.",
    axisId: "axis-decision",
    polarity: 1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "rhythm-02",
    sectionId: "part-1",
    order: 4,
    text: "수업 중에 좋은 이야기가 나오면 준비한 활동을 미뤄 두는 편이다.",
    axisId: "axis-rhythm",
    polarity: -1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "energy-04",
    sectionId: "part-1",
    order: 5,
    text: "수업 준비는 방해받지 않는 조용한 시간에 몰아서 하는 편이다.",
    axisId: "axis-energy",
    polarity: -1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "lens-01",
    sectionId: "part-1",
    order: 6,
    text: "교재 연구를 할 때 활동 순서와 준비물부터 구체적으로 챙기는 편이다.",
    axisId: "axis-lens",
    polarity: 1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "decision-04",
    sectionId: "part-1",
    order: 7,
    text: "자주 늦는 아이에게는 그럴 만한 사정이 있는지부터 살피는 편이다.",
    axisId: "axis-decision",
    polarity: -1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "rhythm-01",
    sectionId: "part-1",
    order: 8,
    text: "학기가 시작되기 전에 한 달 치 수업 흐름을 정해 두어야 마음이 놓인다.",
    axisId: "axis-rhythm",
    polarity: 1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "energy-05",
    sectionId: "part-1",
    order: 9,
    text: "연수에 가면 강의 내용만큼 쉬는 시간의 대화에서 얻는 것이 많다고 느낀다.",
    axisId: "axis-energy",
    polarity: 1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "decision-06",
    sectionId: "part-1",
    order: 10,
    text: "같은 잘못이라도 그 아이가 지나온 사정에 따라 다르게 대하는 편이다.",
    axisId: "axis-decision",
    polarity: -1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "energy-11",
    sectionId: "part-1",
    order: 11,
    text: "여러 선생님과 함께 있는 자리에서도 생각은 속으로 정리하는 편이다.",
    axisId: "axis-energy",
    polarity: -1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "lens-11",
    sectionId: "part-1",
    order: 12,
    text: "생활지도를 할 때 이 행동이 앞으로 어떻게 달라질지 그려 보는 편이다.",
    axisId: "axis-lens",
    polarity: -1,
    weight: 1,
    context: "guidance",
  },
  // ── Part 2 ──────────────────────────────────────────────────────────────
  {
    id: "lens-03",
    sectionId: "part-2",
    order: 13,
    text: "아이를 파악할 때 직접 관찰한 장면과 기록을 근거로 삼는 편이다.",
    axisId: "axis-lens",
    polarity: 1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "rhythm-04",
    sectionId: "part-2",
    order: 14,
    text: "업무는 마감이 가까워졌을 때 오히려 집중이 잘 되는 편이다.",
    axisId: "axis-rhythm",
    polarity: -1,
    weight: 1,
    context: "admin",
  },
  {
    id: "energy-02",
    sectionId: "part-2",
    order: 15,
    text: "점심시간에는 교실에 혼자 있는 시간이 있어야 오후가 편하다.",
    axisId: "axis-energy",
    polarity: -1,
    weight: 1,
    context: "self",
  },
  {
    id: "decision-03",
    sectionId: "part-2",
    order: 16,
    text: "과제를 내지 못한 아이에게는 우리 반이 정한 기준대로 처리하는 편이다.",
    axisId: "axis-decision",
    polarity: 1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "lens-04",
    sectionId: "part-2",
    order: 17,
    text: "아이의 지금 모습보다 앞으로 어떻게 자랄지가 먼저 그려지는 편이다.",
    axisId: "axis-lens",
    polarity: -1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "rhythm-03",
    sectionId: "part-2",
    order: 18,
    text: "공문이나 업무는 마감보다 여유 있게 끝내 두는 편이다.",
    axisId: "axis-rhythm",
    polarity: 1,
    weight: 1,
    context: "admin",
  },
  {
    id: "energy-09",
    sectionId: "part-2",
    order: 19,
    text: "학년 협의회에서 떠오른 생각을 그 자리에서 꺼내 놓는 편이다.",
    axisId: "axis-energy",
    polarity: 1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "lens-05",
    sectionId: "part-2",
    order: 20,
    text: "학부모 상담에서는 그날 교실에서 있었던 일을 사실대로 전하는 편이다.",
    axisId: "axis-lens",
    polarity: 1,
    weight: 1,
    context: "family",
  },
  {
    id: "decision-08",
    sectionId: "part-2",
    order: 21,
    text: "고칠 점을 말하기 전에 그 아이가 받을 마음의 무게를 먼저 헤아리는 편이다.",
    axisId: "axis-decision",
    polarity: -1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "rhythm-06",
    sectionId: "part-2",
    order: 22,
    text: "자세한 계획보다 큰 방향만 정해 두고 시작하는 편이 편하다.",
    axisId: "axis-rhythm",
    polarity: -1,
    weight: 1,
    context: "admin",
  },
  {
    id: "decision-11",
    sectionId: "part-2",
    order: 23,
    text: "학교 행사에서 문제가 생기면 정해진 절차대로 처리하는 편이다.",
    axisId: "axis-decision",
    polarity: 1,
    weight: 1,
    context: "admin",
  },
  {
    id: "rhythm-11",
    sectionId: "part-2",
    order: 24,
    text: "아침에 그날 할 일을 순서대로 적어 두어야 마음이 놓인다.",
    axisId: "axis-rhythm",
    polarity: 1,
    weight: 1,
    context: "self",
  },
  // ── Part 3 ──────────────────────────────────────────────────────────────
  {
    id: "energy-06",
    sectionId: "part-3",
    order: 25,
    text: "회의에서는 다른 사람의 이야기를 충분히 들은 뒤에 말하는 편이다.",
    axisId: "axis-energy",
    polarity: -1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "lens-07",
    sectionId: "part-3",
    order: 26,
    text: "연수에서는 바로 써 볼 수 있는 활동 자료가 가장 도움이 된다고 느낀다.",
    axisId: "axis-lens",
    polarity: 1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "decision-05",
    sectionId: "part-3",
    order: 27,
    text: "역할이나 상을 정할 때는 정해 둔 기준을 그대로 적용하는 편이다.",
    axisId: "axis-decision",
    polarity: 1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "rhythm-08",
    sectionId: "part-3",
    order: 28,
    text: "갑자기 일정이 바뀌어도 그 자리에서 다른 방법을 찾아내는 편이다.",
    axisId: "axis-rhythm",
    polarity: -1,
    weight: 1,
    context: "admin",
  },
  {
    id: "energy-03",
    sectionId: "part-3",
    order: 29,
    text: "수업 아이디어는 혼자 정리할 때보다 동료와 말하며 풀릴 때가 많다고 느낀다.",
    axisId: "axis-energy",
    polarity: 1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "decision-02",
    sectionId: "part-3",
    order: 30,
    text: "다툼을 중재할 때 각자 어떤 마음이었는지를 먼저 듣는 편이다.",
    axisId: "axis-decision",
    polarity: -1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "rhythm-05",
    sectionId: "part-3",
    order: 31,
    text: "다음 주 시간표를 미리 훑어보며 준비물을 챙겨 두는 편이다.",
    axisId: "axis-rhythm",
    polarity: 1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "energy-10",
    sectionId: "part-3",
    order: 32,
    text: "여러 사람과 오래 이야기한 날은 유난히 기운이 빠진다고 느낀다.",
    axisId: "axis-energy",
    polarity: -1,
    weight: 1,
    context: "self",
  },
  {
    id: "lens-06",
    sectionId: "part-3",
    order: 33,
    text: "수업에서 새 내용을 소개할 때 세부보다 전체가 어떤 이야기인지를 먼저 짚어 주는 편이다.",
    axisId: "axis-lens",
    polarity: -1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "decision-07",
    sectionId: "part-3",
    order: 34,
    text: "아이에게 고칠 점을 말할 때 돌려 말하기보다 분명히 짚어 주는 편이다.",
    axisId: "axis-decision",
    polarity: 1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "energy-12",
    sectionId: "part-3",
    order: 35,
    text: "혼자 있는 시간이 길어지면 오히려 답답해지는 편이다.",
    axisId: "axis-energy",
    polarity: 1,
    weight: 1,
    context: "self",
  },
  {
    id: "lens-12",
    sectionId: "part-3",
    order: 36,
    text: "학년 회의에서는 실제로 해 본 사례가 나올 때 가장 도움이 되는 편이다.",
    axisId: "axis-lens",
    polarity: 1,
    weight: 1,
    context: "colleague",
  },
  // ── Part 4 ──────────────────────────────────────────────────────────────
  {
    id: "lens-08",
    sectionId: "part-4",
    order: 37,
    text: "연수에서는 당장 쓸 자료보다 관점을 바꿔 주는 이야기가 오래 남는다고 느낀다.",
    axisId: "axis-lens",
    polarity: -1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "rhythm-07",
    sectionId: "part-4",
    order: 38,
    text: "행사 준비는 역할과 순서를 먼저 정해 두고 시작하는 편이다.",
    axisId: "axis-rhythm",
    polarity: 1,
    weight: 1,
    context: "admin",
  },
  {
    id: "energy-07",
    sectionId: "part-4",
    order: 39,
    text: "힘든 하루를 보낸 날에는 누군가에게 털어놓아야 풀리는 편이다.",
    axisId: "axis-energy",
    polarity: 1,
    weight: 1,
    context: "self",
  },
  {
    id: "decision-09",
    sectionId: "part-4",
    order: 40,
    text: "학부모의 요청이 규정과 어긋나면 어렵더라도 그대로 설명하는 편이다.",
    axisId: "axis-decision",
    polarity: 1,
    weight: 1,
    context: "family",
  },
  {
    id: "lens-09",
    sectionId: "part-4",
    order: 41,
    text: "수업이 잘 됐는지는 아이들이 실제로 해낸 결과물을 보고 판단하는 편이다.",
    axisId: "axis-lens",
    polarity: 1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "rhythm-10",
    sectionId: "part-4",
    order: 42,
    text: "그날 교실 분위기를 보고 활동을 고르는 편이다.",
    axisId: "axis-rhythm",
    polarity: -1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "energy-08",
    sectionId: "part-4",
    order: 43,
    text: "퇴근길에 혼자 있는 시간이 하루를 정리해 준다고 느낀다.",
    axisId: "axis-energy",
    polarity: -1,
    weight: 1,
    context: "self",
  },
  {
    id: "lens-10",
    sectionId: "part-4",
    order: 44,
    text: "학년을 마칠 때 진도보다 아이들이 무엇을 알게 되었는지를 먼저 돌아보는 편이다.",
    axisId: "axis-lens",
    polarity: -1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "decision-10",
    sectionId: "part-4",
    order: 45,
    text: "업무를 나눌 때 각자가 놓인 형편을 살펴 조정하는 편이다.",
    axisId: "axis-decision",
    polarity: -1,
    weight: 1,
    context: "admin",
  },
  {
    id: "rhythm-09",
    sectionId: "part-4",
    order: 46,
    text: "하루가 계획한 순서대로 흘러갔을 때 잘 보냈다고 느낀다.",
    axisId: "axis-rhythm",
    polarity: 1,
    weight: 1,
    context: "self",
  },
  {
    id: "decision-12",
    sectionId: "part-4",
    order: 47,
    text: "함께 일하는 선생님이 힘들어하면 맡은 몫을 다시 나누는 편이다.",
    axisId: "axis-decision",
    polarity: -1,
    weight: 1,
    context: "admin",
  },
  {
    id: "rhythm-12",
    sectionId: "part-4",
    order: 48,
    text: "그날의 힘과 상황에 따라 할 일의 순서를 바꾸는 편이다.",
    axisId: "axis-rhythm",
    polarity: -1,
    weight: 1,
    context: "self",
  },
];
