/**
 * 문항 48개 (contentVersion 4.0.0 — 2026-08-21 확장, DEC-048)
 *
 * 검수안: docs/content/teacher-style-v1-revision.md
 *
 * 배분 규칙 (docs/content/teacher-style-v1.md 5.1)
 *   - 축 4개 × 12문항
 *   - 축마다 polarity +1 여섯 개 / -1 여섯 개 (묵종 편향 상쇄)
 *   - Part마다 네 축이 모두 섞이도록 배치
 *   - 같은 뜻을 뒤집은 짝 문항은 서로 다른 Part에 둠 (바로 옆에 있으면 답이 오염됨)
 *
 * 작성 규칙 (같은 문서 5.2 · realContent.test.ts가 자동 검사)
 *   - 축마다 전용 장면군을 쓴다 — 같은 장면이 두 축에 나오지 않게 해 겹침을 원천 차단
 *   - 교실·학교 상황을 구체적으로, 한 문항에 한 가지만
 *   - 부정문을 쓰지 않고 polarity로 방향을 뒤집음
 *   - 40자 내외, "항상 / 절대" 같은 극단 표현 없음
 *   - 빈도가 아니라 성향을 물음 ("~하는 편이다")
 *   - 반박하기 어려운 문장을 쓰지 않는다 — 모두가 동의하면 사람을 구분하지 못함
 *
 * context는 이 문항이 묻는 장면입니다 (DEC-048). 장면 안에서도 찬반이 한쪽으로
 * 몰리지 않아야 합니다 — 몰리면 응답 습관이 장면 차이로 둔갑합니다.
 *
 * id는 축 이름 + 번호입니다. 문항 순서를 바꿔도 id는 그대로 두세요.
 * (id가 바뀌면 이미 저장된 응답을 못 찾습니다)
 */
export const questions = [
  // ── Part 1 ──────────────────────────────────────────────────────────────
  {
    id: "energy-01",
    sectionId: "part-1",
    order: 1,
    text: "쉬는 시간에는 다른 선생님과 수다를 떠는 편이다.",
    axisId: "axis-energy",
    polarity: 1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "lens-02",
    sectionId: "part-1",
    order: 2,
    text: "단원을 볼 때 이 내용이 아이들의 삶과 어떻게 이어질지 먼저 떠올리는 편이다.",
    axisId: "axis-lens",
    polarity: -1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "decision-01",
    sectionId: "part-1",
    order: 3,
    text: "다툼을 중재할 때 누가 어떤 행동을 했는지부터 정리하는 편이다.",
    axisId: "axis-decision",
    polarity: 1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "rhythm-02",
    sectionId: "part-1",
    order: 4,
    text: "수업 중에 좋은 이야기가 나오면 준비한 활동을 미뤄 두는 편이다.",
    axisId: "axis-rhythm",
    polarity: -1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "energy-04",
    sectionId: "part-1",
    order: 5,
    text: "수업 준비는 방해받지 않는 조용한 시간에 몰아서 하는 편이다.",
    axisId: "axis-energy",
    polarity: -1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "lens-01",
    sectionId: "part-1",
    order: 6,
    text: "수업 준비를 할 때 수업의 흐름 구상보다 먼저 수업에 쓸 자료부터 준비하는 편이다.",
    axisId: "axis-lens",
    polarity: 1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "decision-04",
    sectionId: "part-1",
    order: 7,
    text: "자주 늦는 학생이라도 그럴 사정이 있는지부터 듣는 편이다.",
    axisId: "axis-decision",
    polarity: -1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "rhythm-01",
    sectionId: "part-1",
    order: 8,
    text: "몇 주 치나 한 달 치 수업 준비를 해놓아야 마음이 편하다.",
    axisId: "axis-rhythm",
    polarity: 1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "energy-05",
    sectionId: "part-1",
    order: 9,
    text: "복도에서 선생님들을 마주치면 먼저 말을 거는 편이다.",
    axisId: "axis-energy",
    polarity: 1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "decision-06",
    sectionId: "part-1",
    order: 10,
    text: "숙제를 안 한 학생에게도 사정을 먼저 묻고 참작하는 편이다.",
    axisId: "axis-decision",
    polarity: -1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "energy-11",
    sectionId: "part-1",
    order: 11,
    text: "교무실을 들르면 할 일만 하고 교실로 돌아오는 편이다.",
    axisId: "axis-energy",
    polarity: -1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "lens-11",
    sectionId: "part-1",
    order: 12,
    text: "현재 손이 정말 많이 가게 하는 학생도 학기말에는 달라질 수 있을 거라 믿는 편이다.",
    axisId: "axis-lens",
    polarity: -1,
    weight: 1,
    context: "guidance",
  },
  // ── Part 2 ──────────────────────────────────────────────────────────────
  {
    id: "lens-03",
    sectionId: "part-2",
    order: 13,
    text: "학생이 달라졌는지는 직감에 의존하기보다는 관찰 기록물로 판단하는 편이다.",
    axisId: "axis-lens",
    polarity: 1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "rhythm-04",
    sectionId: "part-2",
    order: 14,
    text: "업무는 마감이 가까워졌을 때 오히려 집중이 잘 되는 편이다.",
    axisId: "axis-rhythm",
    polarity: -1,
    weight: 1,
    context: "admin",
  },
  {
    id: "energy-02",
    sectionId: "part-2",
    order: 15,
    text: "빈 시간이 생기면 동료와 어울리기보다 혼자 쉬는 편이다.",
    axisId: "axis-energy",
    polarity: -1,
    weight: 1,
    context: "self",
  },
  {
    id: "decision-03",
    sectionId: "part-2",
    order: 16,
    text: "잘못을 저지른 학생에게는 사정이 있더라도 학급에서 정한 기준대로 처벌하는 편이다.",
    axisId: "axis-decision",
    polarity: 1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "lens-04",
    sectionId: "part-2",
    order: 17,
    text: "아이를 볼 때 몇 년 뒤 어떤 어른이 되어 있을지가 자주 궁금해지는 편이다.",
    axisId: "axis-lens",
    polarity: -1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "rhythm-03",
    sectionId: "part-2",
    order: 18,
    text: "공문은 마감 기한을 넉넉히 두고 일찍 처리하는 편이다.",
    axisId: "axis-rhythm",
    polarity: 1,
    weight: 1,
    context: "admin",
  },
  {
    id: "energy-09",
    sectionId: "part-2",
    order: 19,
    text: "학년 협의회에서 떠오른 생각을 그 자리에서 꺼내 놓는 편이다.",
    axisId: "axis-energy",
    polarity: 1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "lens-05",
    sectionId: "part-2",
    order: 20,
    text: "학부모 상담 시, 학생에 대해서 포장하기보다는 사실대로 전하는 편이다.",
    axisId: "axis-lens",
    polarity: 1,
    weight: 1,
    context: "family",
  },
  {
    id: "decision-08",
    sectionId: "part-2",
    order: 21,
    text: "고칠 점을 말할 때 그 아이 표정을 보며 말투를 바꾸는 편이다.",
    axisId: "axis-decision",
    polarity: -1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "rhythm-06",
    sectionId: "part-2",
    order: 22,
    text: "새 업무를 맡으면 디테일한 계획을 짜기보다는 일단 시작해 보는 편이다.",
    axisId: "axis-rhythm",
    polarity: -1,
    weight: 1,
    context: "admin",
  },
  {
    id: "decision-11",
    sectionId: "part-2",
    order: 23,
    text: "학교 행사에서 문제가 생기면 정해진 절차대로 처리하는 편이다.",
    axisId: "axis-decision",
    polarity: 1,
    weight: 1,
    context: "admin",
  },
  {
    id: "rhythm-11",
    sectionId: "part-2",
    order: 24,
    text: "아침에 그날 할 일을 순서대로 적어 두어야 마음이 놓인다.",
    axisId: "axis-rhythm",
    polarity: 1,
    weight: 1,
    context: "self",
  },
  // ── Part 3 ──────────────────────────────────────────────────────────────
  {
    id: "energy-06",
    sectionId: "part-3",
    order: 25,
    text: "회의나 모임에서는 자주 발언하는 것보다 들으며 정리하는 편이다.",
    axisId: "axis-energy",
    polarity: -1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "lens-07",
    sectionId: "part-3",
    order: 26,
    text: "연수에서는 이론 강의보다 바로 쓸 수 있는 활동 자료가 더 도움이 된다고 느낀다.",
    axisId: "axis-lens",
    polarity: 1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "decision-05",
    sectionId: "part-3",
    order: 27,
    text: "정해 둔 학급 규칙은 상황에 따라 바꾸기보다, 일관되게 적용하는 것이 중요하다고 생각한다.",
    axisId: "axis-decision",
    polarity: 1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "rhythm-08",
    sectionId: "part-3",
    order: 28,
    text: "할 일의 순서는 그날 상황을 보고 그때그때 정하는 편이다.",
    axisId: "axis-rhythm",
    polarity: -1,
    weight: 1,
    context: "admin",
  },
  {
    id: "energy-03",
    sectionId: "part-3",
    order: 29,
    text: "업무에 관해 모르는게 있거나 고민이 있으면, 혼자 찾아보기보다는 다른 선생님과의 대화를 통해 해답을 찾는 편이다.",
    axisId: "axis-energy",
    polarity: 1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "decision-02",
    sectionId: "part-3",
    order: 30,
    text: "다툼을 중재할 때 각자 어떤 마음이었는지를 먼저 듣는 편이다.",
    axisId: "axis-decision",
    polarity: -1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "rhythm-05",
    sectionId: "part-3",
    order: 31,
    text: "수업에 필요한 교구는 당일이나 하루 전보다 더 일찍 미리 챙겨 두는 편이다.",
    axisId: "axis-rhythm",
    polarity: 1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "energy-10",
    sectionId: "part-3",
    order: 32,
    text: "사람을 많이 만난 날은 다음 날 혼자 보내고 싶어지는 편이다.",
    axisId: "axis-energy",
    polarity: -1,
    weight: 1,
    context: "self",
  },
  {
    id: "lens-06",
    sectionId: "part-3",
    order: 33,
    text: "새 단원을 시작할 때 오늘 배울 내용보다 앞으로의 흐름을 먼저 안내하는 편이다.",
    axisId: "axis-lens",
    polarity: -1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "decision-07",
    sectionId: "part-3",
    order: 34,
    text: "학생 평가를 할 때 학생이 기울인 노력보다는 성과에 우선순위를 두어 채점하는 편이다.",
    axisId: "axis-decision",
    polarity: 1,
    weight: 1,
    context: "guidance",
  },
  {
    id: "energy-12",
    sectionId: "part-3",
    order: 35,
    text: "방학이 길어지면 슬슬 동료 선생님들이 보고 싶어지는 편이다.",
    axisId: "axis-energy",
    polarity: 1,
    weight: 1,
    context: "self",
  },
  {
    id: "lens-12",
    sectionId: "part-3",
    order: 36,
    text: "수업 협의회를 할 때, 수업에 대한 신선한 아이디어나 관점보다 선생님들의 실제 사례를 듣는게 도움이 된다.",
    axisId: "axis-lens",
    polarity: 1,
    weight: 1,
    context: "colleague",
  },
  // ── Part 4 ──────────────────────────────────────────────────────────────
  {
    id: "lens-08",
    sectionId: "part-4",
    order: 37,
    text: "연수에서 하나의 사례를 들으면 거기서 여러 응용 방안을 상상해 보는 편이다.",
    axisId: "axis-lens",
    polarity: -1,
    weight: 1,
    context: "colleague",
  },
  {
    id: "rhythm-07",
    sectionId: "part-4",
    order: 38,
    text: "학교 행사를 맡으면 해야 할 일을 날짜별이나 시간별로 나눠 정리해 두는 편이다.",
    axisId: "axis-rhythm",
    polarity: 1,
    weight: 1,
    context: "admin",
  },
  {
    id: "energy-07",
    sectionId: "part-4",
    order: 39,
    text: "마음이 복잡할 때는 누군가에게 꺼내 놓아야 정리되는 편이다.",
    axisId: "axis-energy",
    polarity: 1,
    weight: 1,
    context: "self",
  },
  {
    id: "decision-09",
    sectionId: "part-4",
    order: 40,
    text: "학부모가 요청한 부탁이 사소하더라도 학교 규정과 어긋나면 원칙대로 거절하는 편이다.",
    axisId: "axis-decision",
    polarity: 1,
    weight: 1,
    context: "family",
  },
  {
    id: "lens-09",
    sectionId: "part-4",
    order: 41,
    text: "수업이 잘 됐는지는 아이들이 만들어 낸 산출물로 확인하는 편이다.",
    axisId: "axis-lens",
    polarity: 1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "rhythm-10",
    sectionId: "part-4",
    order: 42,
    text: "수업 중, 계획한 활동이 있어도 수업 분위기를 보고 즉각 다른 활동으로 조정하곤 한다.",
    axisId: "axis-rhythm",
    polarity: -1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "energy-08",
    sectionId: "part-4",
    order: 43,
    text: "퇴근길에는 통화나 메시지를 하기 보다 조용히 혼자 퇴근하는게 좋다.",
    axisId: "axis-energy",
    polarity: -1,
    weight: 1,
    context: "self",
  },
  {
    id: "lens-10",
    sectionId: "part-4",
    order: 44,
    text: "학년을 마무리할 때 올해 가르치지 못한 부분들이 내년 담임에게 어떤 영향을 줄지 생각하는 편이다.",
    axisId: "axis-lens",
    polarity: -1,
    weight: 1,
    context: "lesson",
  },
  {
    id: "decision-10",
    sectionId: "part-4",
    order: 45,
    text: "업무 분장을 할 때 균등 배분보다 각자 사정에 맞추는 게 맞다고 생각하는 편이다.",
    axisId: "axis-decision",
    polarity: -1,
    weight: 1,
    context: "admin",
  },
  {
    id: "rhythm-09",
    sectionId: "part-4",
    order: 46,
    text: "쉬는 날에도 대략적인 시간 계획을 세워야 마음이 놓이는 편이다.",
    axisId: "axis-rhythm",
    polarity: 1,
    weight: 1,
    context: "self",
  },
  {
    id: "decision-12",
    sectionId: "part-4",
    order: 47,
    text: "급한 상황이면 결재를 받기 전에 먼저 실행하고 나중에 보고하는 편이다.",
    axisId: "axis-decision",
    polarity: -1,
    weight: 1,
    context: "admin",
  },
  {
    id: "rhythm-12",
    sectionId: "part-4",
    order: 48,
    text: "오늘 하기로 한 일이 있어도 느낌이 오지 않으면 다음 날로 넘기곤 한다.",
    axisId: "axis-rhythm",
    polarity: -1,
    weight: 1,
    context: "self",
  },
];
