/**
 * 방향·강도·균형을 함께 반영하는 결과 상단 서술 (DEC-046).
 *
 * 한 축당 균형 1개, 방향 2개 × 강도 2개를 둡니다.
 * 문장은 해당 축이 실제로 물은 맥락 안에서만 설명합니다.
 */
export const resultNarrative = {
  balancedTitle: "상황에 맞춰 폭넓게 움직이는 선생님",
  balancedRhythm:
    "한 관점에서 두 방식이 정확히 같은 무게로 나왔습니다. 그래서 이 결과는 한쪽 이름을 붙이는 대신, 상황에 따라 방식을 바꿔 쓰는 모습으로 읽습니다. 어느 장면에서 어느 쪽을 골랐는지 떠올려 보면 나에게 맞는 설명이 더 또렷해집니다.",
  balancedOneLiner:
    "네 가지 관점에서 서로 다른 방식을 고르게 활용하는 모습이 나타납니다.",
  balancedAxisNote:
    "상황에 따라 두 방식을 폭넓게 활용하는 관점도 함께 나타납니다.",
  // 0점이지만 응답이 갈리지 않은 축 (DEC-053).
  // '균형'이라고 부르면, 답을 고르지 않은 분께 "두 방식을 고루 쓰신다"고 말하게 됩니다.
  unreadableAxisLabel: "읽기 어려움",
  unreadableAxisNote:
    "이 관점은 문항마다 답이 비슷해서 어느 쪽인지 읽기 어려웠어요. 다시 검사하실 때 조금 더 갈라서 답해 주시면 또렷하게 보실 수 있습니다.",
  scopeNote: "이 검사는 학생과 나누는 말의 양이나 마감을 지키는 습관을 평가하지 않습니다.",
  emphasisTerms: [
    "몇 달 뒤 달라져 있을 모습",
    "누군가에게 설명해 볼 때",
    "여럿이 함께 이해할 기준",
    "더 나은 방법이 보이면",
    "그것들이 만드는 방향",
    "무엇을 기준으로 볼지",
    "설명할 수 없는 결정",
    "이야기할 사람을 찾는",
    "현장에서 방법을 조정",
    "같은 답이 나오는지",
    "관찰한 장면과 자료",
    "방해받지 않는 시간",
    "사정을 모르는 채로",
    "속으로 한 번 굴려",
    "순서를 한 번 훑어",
    "앞으로 이어질 흐름",
    "확인되지 않은 전제",
    "각자가 놓인 상황",
    "그날 상황에 맞는",
    "놓인 형편에 따라",
    "동료와 이야기하며",
    "무엇을 언제 할지",
    "순서가 정해진 뒤",
    "순서를 미리 정해",
    "준비가 덜 된 채",
    "다음 수를 찾는",
    "말로 꺼내 놓고",
    "실제로 어땠는지",
    "어디로 이어질지",
    "이야기하며 정리",
    "지금 확인된 것",
    "혼자 있는 시간",
    "기록과 결과물",
    "미리 정해 두",
    "앞으로의 흐름",
    "어디로 가는가",
    "어떤 상황인지",
    "혼자 있을 때",
    "혼자 정리하는",
    "각자의 상황",
    "관찰한 사실",
    "기준을 먼저",
    "기준을 앞에",
    "상황을 먼저",
    "해 보는 중",
    "현장에 맞춰",
    "혼자 정리할",
    "말한 뒤",
  ],
  balancedGuidance: {
    shiningMoments: [
      {
        scene: "수업",
        situation: "두 방식이 갈렸던 날",
        text: "같은 단원을 어느 날은 준비한 대로, 어느 날은 교실 반응에 맞춰 가르칩니다.",
      },
      {
        scene: "업무",
        situation: "일의 성격이 다를 때",
        text: "정해진 절차가 있는 일과 새로 만들어야 하는 일에 서로 다른 방식을 씁니다.",
      },
      {
        scene: "생활지도",
        situation: "아이마다 다르게 대할 때",
        text: "공통 기준을 세울 때와 그 아이의 상황을 볼 때를 구분해 움직입니다.",
      },
    ],
    underPressure: [
      {
        scene: "업무",
        situation: "일이 몰릴 때",
        text: "평소에는 둘을 오가던 것이, 바빠지면 한쪽 방식으로만 기웁니다.",
      },
      {
        scene: "동료",
        situation: "선택이 바뀌었을 때",
        text: "무엇을 보고 바꿨는지 말해 두지 않으면, 동료는 판단 과정을 몰라 다시 묻습니다.",
      },
      {
        scene: "수업",
        situation: "시간이 부족할 때",
        text: "익숙한 쪽 방식을 먼저 집어서, 다른 방식을 꺼낼 여유가 줄어듭니다.",
      },
    ],
    withColleagues: [
      {
        scene: "동료",
        situation: "역할을 나눌 때",
        text: "한 방식에 매이지 않아, 비어 있는 자리를 맡기가 수월합니다.",
      },
      {
        scene: "업무",
        situation: "새 일을 시작할 때",
        text: "이번에 필요한 방식과 다시 판단할 시점을 먼저 맞춥니다.",
      },
      {
        scene: "동료",
        situation: "의견이 갈릴 때",
        text: "양쪽 방식을 다 겪어 봤기 때문에, 서로의 이유를 옆에서 옮깁니다.",
      },
    ],
    collaboration: {
      naturalFit: [
        "어느 한쪽 이름에 맞추기보다, 이번 장면에서 자연스러웠던 방식과 그 이유를 나누기 쉬워요.",
        "서로 다른 방식을 사용해 본 경험이 있다면, 각 장면의 조건을 비교해 공통점을 찾아보세요.",
      ],
      needsTuning: [
        "균형 결과가 언제나 중간을 택한다는 뜻은 아니므로, 이번 일에서 선호하는 방식은 따로 말해 두세요.",
        "상황에 따라 방법을 바꿨다면 바꾼 이유와 다시 확인할 시점을 함께 알려 주세요.",
      ],
    },
    nextSteps: [
      "균형으로 나온 관점 하나를 골라, 최근 각 방식을 사용한 장면이 있는지 적어 보세요.",
      "두 장면에서 선택이 달라진 조건을 한 가지씩 표시해 보세요.",
      "다음 비슷한 일이 생기면 무엇을 먼저 확인할지 정해 보세요.",
    ],
    talkingPoints: [
      "같은 일에서도 상황에 따라 다른 방식을 쓴 적이 있나요?",
      "두 방식 중 하나를 더 선호하게 되는 조건은 무엇인가요?",
      "동료에게 내 선택의 이유를 어떻게 설명하나요?",
    ],
  },
  axes: [
    {
      axisId: "axis-energy",
      counterEvidence:
        "최근 한 달이 유난히 바빴거나 함께 일하는 선생님이 바뀌었다면, 평소 모습이 아니라 그 시기의 상황이 답에 실렸을 수 있어요.",
      readings: [
        {
          intensityBandId: "balanced",
          direction: "balanced",
          headline: "이야기와 혼자 정리를 비슷하게 쓰는 편",
          summary: "동료와 이야기하며 정리할 때와 혼자 정리할 때가 비슷하게 나타나요.",
          rhythm: "회의에서 말하며 정리한 날도, 교실에 돌아와 혼자 정리한 날도 있습니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "positive",
          headline: "두 방식을 쓰되 이야기 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 동료와 이야기하며 정리하는 쪽에 조금 더 가까워요.",
          rhythm: "학년 협의처럼 여러 사람이 모인 자리에서 조금 더 그렇습니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "negative",
          headline: "두 방식을 쓰되 혼자 정리하는 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 혼자 정리하는 쪽에 조금 더 가까워요.",
          rhythm: "아이들이 빠져나간 교실처럼 조용한 자리에서 조금 더 그렇습니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "positive",
          headline: "이야기하며 정리한 장면이 있는 편",
          summary: "말로 꺼내 놓고 나면 흩어져 있던 생각이 한 줄로 정리되곤 해요.",
          rhythm: "어떤 장면에서는 옆 반 선생님과 이야기하다 결론이 잡힙니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "negative",
          headline: "혼자 정리한 장면이 있는 편",
          summary: "말을 꺼내기 전에 속으로 한 번 굴려 보고 나면 생각이 또렷해지곤 해요.",
          rhythm: "어떤 장면에서는 퇴근길처럼 혼자 있는 시간에 생각이 정리됩니다.",
        },
        {
          intensityBandId: "clear",
          direction: "positive",
          headline: "여러 장면에서 이야기하며 정리하는 편",
          summary: "머릿속으로만 굴릴 때보다, 누군가에게 설명해 볼 때 결론이 빨리 잡혀요.",
          rhythm: "학년 회의나 동학년 대화처럼 사람이 모인 자리에서 특히 그렇습니다.",
        },
        {
          intensityBandId: "clear",
          direction: "negative",
          headline: "여러 장면에서 혼자 정리하는 편",
          summary: "여럿이 오간 이야기도 혼자 있는 시간을 거쳐야 내 결론이 돼요.",
          rhythm: "아이들이 나간 뒤의 교실처럼 조용한 자리에서 특히 그렇습니다.",
        },
        {
          intensityBandId: "strong",
          direction: "positive",
          headline: "장면이 바뀌어도 이야기하며 정리하는 편",
          summary: "막히는 일이 있으면 혼자 붙들기보다 먼저 이야기할 사람을 찾는 쪽이에요.",
          rhythm: "수업 준비든 업무든, 막히면 먼저 이야기할 사람을 찾습니다.",
        },
        {
          intensityBandId: "strong",
          direction: "negative",
          headline: "장면이 바뀌어도 혼자 정리하는 편",
          summary: "방해받지 않는 시간이 확보돼야 일이 앞으로 나가는 쪽이에요.",
          rhythm: "수업 준비든 업무든, 먼저 혼자 앉을 시간을 만듭니다.",
        },
        {
          intensityBandId: "defining",
          direction: "positive",
          headline: "대부분의 장면에서 이야기하며 정리하는 편",
          summary: "생각이 정리되는 시점이 대체로 말한 뒤라, 대화가 곧 일의 한 과정이에요.",
          rhythm: "혼자 정리해도 되는 일까지 누군가에게 한 번 말해 보고 넘어갑니다.",
        },
        {
          intensityBandId: "defining",
          direction: "negative",
          headline: "대부분의 장면에서 혼자 정리하는 편",
          summary: "생각이 정리되는 시점이 대체로 혼자 있을 때라, 그 시간이 곧 일의 한 과정이에요.",
          rhythm: "회의 중에도 잠깐 자리를 떠나 혼자 정리하고 돌아옵니다.",
        },
      ],
    },
    {
      axisId: "axis-lens",
      counterEvidence:
        "올해 맡은 학년이나 교과가 크게 달라졌다면, 평소 보는 방식이 아니라 지금 익히는 중인 방식이 답에 실렸을 수 있어요.",
      readings: [
        {
          intensityBandId: "balanced",
          direction: "balanced",
          headline: "사실과 흐름을 비슷하게 보는 편",
          summary: "관찰한 사실을 살필 때와 앞으로의 흐름을 그릴 때가 비슷하게 나타나요.",
          rhythm: "아이 기록을 펼쳐 볼 때도, 몇 달 뒤 모습을 떠올릴 때도 있습니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "positive",
          headline: "두 방식을 쓰되 관찰한 사실 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 관찰한 장면과 자료 쪽에 조금 더 가까워요.",
          rhythm: "평가 결과나 활동지처럼 남아 있는 자료를 볼 때 조금 더 그렇습니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "negative",
          headline: "두 방식을 쓰되 앞으로의 흐름 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 앞으로 이어질 흐름 쪽에 조금 더 가까워요.",
          rhythm: "학기 계획을 세울 때처럼 앞을 내다보는 자리에서 조금 더 그렇습니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "positive",
          headline: "관찰한 사실에서 출발한 장면이 있는 편",
          summary: "이야기가 커질 때 실제로 어땠는지를 한 번 짚고 넘어가곤 해요.",
          rhythm: "어떤 장면에서는 상담을 앞두고 그동안의 기록을 먼저 꺼내 봅니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "negative",
          headline: "앞으로의 흐름을 먼저 그린 장면이 있는 편",
          summary: "눈앞의 장면을 보면서 이게 어디로 이어질지가 함께 떠오르곤 해요.",
          rhythm: "어떤 장면에서는 수업 중 한 장면을 보고 다음 단원이 떠오릅니다.",
        },
        {
          intensityBandId: "clear",
          direction: "positive",
          headline: "여러 장면에서 관찰한 사실을 먼저 보는 편",
          summary: "판단이 갈리면 기억보다 남아 있는 기록과 결과물을 먼저 꺼내요.",
          rhythm: "교재 연구나 상담 준비처럼 자료가 필요한 자리에서 특히 그렇습니다.",
        },
        {
          intensityBandId: "clear",
          direction: "negative",
          headline: "여러 장면에서 앞으로의 흐름을 먼저 보는 편",
          summary: "지금의 모습보다 몇 달 뒤 달라져 있을 모습이 먼저 그려져요.",
          rhythm: "학기 계획이나 새 단원을 짤 때처럼 앞을 그리는 자리에서 특히 그렇습니다.",
        },
        {
          intensityBandId: "strong",
          direction: "positive",
          headline: "장면이 바뀌어도 사실에서 출발하는 편",
          summary: "확인되지 않은 전제 위에서는 다음 단계로 잘 넘어가지 않는 쪽이에요.",
          rhythm: "아이 이야기를 나눌 때도 언제 무슨 일이 있었는지부터 확인합니다.",
        },
        {
          intensityBandId: "strong",
          direction: "negative",
          headline: "장면이 바뀌어도 흐름을 먼저 그리는 편",
          summary: "낱낱의 사실보다 그것들이 만드는 방향이 먼저 눈에 들어오는 쪽이에요.",
          rhythm: "아이 이야기를 나눌 때도 이 아이가 어디로 갈지부터 이야기합니다.",
        },
        {
          intensityBandId: "defining",
          direction: "positive",
          headline: "대부분의 장면에서 사실을 먼저 보는 편",
          summary: "무엇을 정하든 출발점이 지금 확인된 것이라, 근거가 늘 앞에 놓여요.",
          rhythm: "연수에서 새 방법을 들어도 우리 반 자료에 먼저 맞춰 봅니다.",
        },
        {
          intensityBandId: "defining",
          direction: "negative",
          headline: "대부분의 장면에서 흐름을 먼저 보는 편",
          summary: "무엇을 보든 그래서 어디로 가는가가 먼저라, 방향이 늘 앞에 놓여요.",
          rhythm: "연수에서 새 방법을 들으면 우리 반에 어떻게 이어질지부터 그립니다.",
        },
      ],
    },
    {
      axisId: "axis-decision",
      counterEvidence:
        "최근 판단이 어려웠던 일이 하나 크게 남아 있다면, 평소 기준이 아니라 그 일의 기억이 답을 끌어당겼을 수 있어요.",
      readings: [
        {
          intensityBandId: "balanced",
          direction: "balanced",
          headline: "기준과 상황을 비슷하게 살피는 편",
          summary: "정한 기준을 확인할 때와 각자의 상황을 살필 때가 비슷하게 나타나요.",
          rhythm: "약속대로 처리한 일도, 그 아이 사정을 먼저 들은 일도 있습니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "positive",
          headline: "두 방식을 쓰되 기준 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 여럿이 함께 이해할 기준 쪽에 조금 더 가까워요.",
          rhythm: "학급 규칙을 정할 때처럼 모두에게 같이 적용되는 자리에서 조금 더 그렇습니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "negative",
          headline: "두 방식을 쓰되 상황 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 각자가 놓인 상황 쪽에 조금 더 가까워요.",
          rhythm: "한 아이와 따로 이야기하는 자리에서 조금 더 그렇습니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "positive",
          headline: "기준을 먼저 확인한 장면이 있는 편",
          summary: "정하기 전에 무엇을 기준으로 볼지를 한 번 확인하곤 해요.",
          rhythm: "어떤 장면에서는 다툼을 중재할 때 먼저 약속을 확인합니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "negative",
          headline: "상황을 먼저 살핀 장면이 있는 편",
          summary: "정하기 전에 이 사람이 지금 어떤 상황인지가 먼저 걸리곤 해요.",
          rhythm: "어떤 장면에서는 다툼을 중재할 때 그 아이의 하루를 먼저 묻습니다.",
        },
        {
          intensityBandId: "clear",
          direction: "positive",
          headline: "여러 장면에서 기준을 먼저 확인하는 편",
          summary: "같은 일이 다시 왔을 때 같은 답이 나오는지를 신경 쓰는 편이에요.",
          rhythm: "생활지도나 업무를 나눌 때처럼 여러 사람이 얽힌 자리에서 특히 그렇습니다.",
        },
        {
          intensityBandId: "clear",
          direction: "negative",
          headline: "여러 장면에서 상황을 먼저 살피는 편",
          summary: "같은 규칙도 놓인 형편에 따라 다르게 적용될 수 있다고 보는 편이에요.",
          rhythm: "상담이나 생활지도처럼 한 사람의 사정이 걸린 자리에서 특히 그렇습니다.",
        },
        {
          intensityBandId: "strong",
          direction: "positive",
          headline: "장면이 바뀌어도 기준을 앞에 두는 편",
          summary: "남에게 설명할 수 없는 결정은 잘 내리지 않는 쪽이에요.",
          rhythm: "학부모 상담에서도 같은 일에는 같은 답이 나오도록 말합니다.",
        },
        {
          intensityBandId: "strong",
          direction: "negative",
          headline: "장면이 바뀌어도 상황을 앞에 두는 편",
          summary: "사정을 모르는 채로는 결정을 늦추더라도 먼저 들어 보는 쪽이에요.",
          rhythm: "학부모 상담에서도 그 집의 형편을 들은 뒤에 답을 정합니다.",
        },
        {
          intensityBandId: "defining",
          direction: "positive",
          headline: "대부분의 장면에서 기준을 앞에 두는 편",
          summary: "판단의 출발점이 늘 기준이라, 결정보다 기준을 먼저 세워 두는 편이에요.",
          rhythm: "새 일이 생기면 결정보다 기준을 먼저 만들어 놓습니다.",
        },
        {
          intensityBandId: "defining",
          direction: "negative",
          headline: "대부분의 장면에서 상황을 앞에 두는 편",
          summary: "판단의 출발점이 늘 그 사람의 자리라, 규칙보다 상황을 먼저 읽는 편이에요.",
          rhythm: "새 일이 생기면 누가 어떤 형편인지부터 확인합니다.",
        },
      ],
    },
    {
      axisId: "axis-rhythm",
      counterEvidence:
        "학기 초처럼 일정이 몰리는 시기에 답했다면, 평소 리듬이 아니라 그 시기의 업무량이 답에 실렸을 수 있어요.",
      readings: [
        {
          intensityBandId: "balanced",
          direction: "balanced",
          headline: "계획과 조정을 비슷하게 쓰는 편",
          summary: "미리 정해 두고 시작할 때와 현장에서 조정할 때가 비슷하게 나타나요.",
          rhythm: "짜 둔 대로 간 주도 있고, 그날 상황에 맞춰 바꾼 주도 있습니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "positive",
          headline: "두 방식을 쓰되 미리 정해 두는 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 순서를 미리 정해 두는 쪽에 조금 더 가까워요.",
          rhythm: "학기 초처럼 준비할 것이 많은 시기에 조금 더 그렇습니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "negative",
          headline: "두 방식을 쓰되 현장에서 조정하는 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 현장에서 방법을 조정하는 쪽에 조금 더 가까워요.",
          rhythm: "행사처럼 변수가 많은 일에서 조금 더 그렇습니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "positive",
          headline: "미리 정해 두고 시작한 장면이 있는 편",
          summary: "시작하기 전에 순서를 한 번 훑어 두면 마음이 놓이곤 해요.",
          rhythm: "어떤 장면에서는 다음 주 수업을 금요일에 미리 훑어 둡니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "negative",
          headline: "현장에서 조정한 장면이 있는 편",
          summary: "해 보면서 더 나은 방법이 보이면 그쪽으로 바꾸곤 해요.",
          rhythm: "어떤 장면에서는 수업 중에 더 나은 활동이 보이면 바로 바꿉니다.",
        },
        {
          intensityBandId: "clear",
          direction: "positive",
          headline: "여러 장면에서 미리 정해 두는 편",
          summary: "무엇을 언제 할지가 보이면 그때부터 속도가 붙는 편이에요.",
          rhythm: "수업 준비나 공문 처리처럼 순서가 있는 일에서 특히 그렇습니다.",
        },
        {
          intensityBandId: "clear",
          direction: "negative",
          headline: "여러 장면에서 현장에 맞춰 조정하는 편",
          summary: "정해 둔 대로보다 그날 상황에 맞는 쪽을 고르는 편이에요.",
          rhythm: "수업이나 행사처럼 그날 분위기가 걸린 일에서 특히 그렇습니다.",
        },
        {
          intensityBandId: "strong",
          direction: "positive",
          headline: "장면이 바뀌어도 미리 정해 두는 편",
          summary: "준비가 덜 된 채 출발하는 것을 잘 견디지 않는 쪽이에요.",
          rhythm: "갑자기 일이 들어와도 순서를 다시 짜 놓고 시작합니다.",
        },
        {
          intensityBandId: "strong",
          direction: "negative",
          headline: "장면이 바뀌어도 현장에 맞춰 조정하는 편",
          summary: "흐름이 어긋나도 크게 흔들리지 않고 다음 수를 찾는 쪽이에요.",
          rhythm: "갑자기 일이 들어와도 하던 것을 접고 바로 그 일에 붙습니다.",
        },
        {
          intensityBandId: "defining",
          direction: "positive",
          headline: "대부분의 장면에서 미리 정해 두는 편",
          summary: "일이 시작되는 시점이 대체로 순서가 정해진 뒤예요.",
          rhythm: "하루를 여는 아침에도 오늘 할 일을 먼저 적어 둡니다.",
        },
        {
          intensityBandId: "defining",
          direction: "negative",
          headline: "대부분의 장면에서 현장에 맞춰 조정하는 편",
          summary: "방법이 정해지는 시점이 대체로 해 보는 중이에요.",
          rhythm: "하루를 여는 아침에도 교실 분위기를 보고 순서를 정합니다.",
        },
      ],
    },
  ],
} as const;
