/**
 * 방향·강도·균형을 함께 반영하는 결과 상단 서술 (DEC-046).
 *
 * 한 축당 균형 1개, 방향 2개 × 강도 2개를 둡니다.
 * 문장은 해당 축이 실제로 물은 맥락 안에서만 설명합니다.
 */
export const resultNarrative = {
  balancedTitle: "상황에 맞춰 폭넓게 움직이는 교직 리듬",
  balancedOneLiner:
    "네 가지 관점에서 서로 다른 방식을 고르게 활용하는 모습이 나타납니다.",
  balancedAxisNote:
    "상황에 따라 두 방식을 폭넓게 활용하는 관점도 함께 나타납니다.",
  scopeNote: "이 검사는 학생과 나누는 말의 양이나 마감을 지키는 습관을 평가하지 않습니다.",
  emphasisTerms: [
    "몇 달 뒤 달라져 있을 모습",
    "누군가에게 설명해 볼 때",
    "여럿이 함께 이해할 기준",
    "더 나은 방법이 보이면",
    "그것들이 만드는 방향",
    "동료와 이야기를 나눈",
    "무엇을 기준으로 볼지",
    "설명할 수 없는 결정",
    "이야기할 사람을 찾는",
    "현장에서 방법을 조정",
    "같은 답이 나오는지",
    "관찰한 장면과 자료",
    "방해받지 않는 시간",
    "사정을 모르는 채로",
    "속으로 한 번 굴려",
    "순서를 한 번 훑어",
    "순서와 준비를 먼저",
    "앞으로 이어질 흐름",
    "확인되지 않은 전제",
    "각자가 놓인 상황",
    "그날 상황에 맞는",
    "그때 상황에 맞춰",
    "놓인 형편에 따라",
    "동료와 이야기하며",
    "무엇을 언제 할지",
    "순서가 정해진 뒤",
    "순서를 먼저 정해",
    "순서를 미리 정해",
    "준비가 덜 된 채",
    "현장 상황에 맞춰",
    "다음 수를 찾는",
    "말로 꺼내 놓고",
    "실제로 어땠는지",
    "어디로 이어질지",
    "이야기하며 정리",
    "지금 확인된 것",
    "혼자 있는 시간",
    "기록과 결과물",
    "미리 정해 두",
    "앞으로의 흐름",
    "어디로 가는가",
    "어떤 상황인지",
    "정해 둔 기준",
    "혼자 있을 때",
    "혼자 정리하는",
    "각자의 상황",
    "관찰한 사실",
    "기준을 먼저",
    "기준을 앞에",
    "상황을 먼저",
    "해 보는 중",
    "현장에 맞춰",
    "혼자 정리할",
    "확인한 사실",
    "큰 방향만",
    "말한 뒤",
  ],
  balancedGuidance: {
    shiningMoments: [
      {
        scene: "수업",
        text: "두 방식 가운데 어느 쪽을 선택했는지 실제 장면을 떠올리고, 선택이 달라진 조건이 있었는지 확인해 보세요.",
      },
      {
        scene: "업무",
        text: "한쪽 방식으로 단정하기보다, 업무의 성격에 따라 달라진 선택과 그 근거를 살펴보세요.",
      },
      {
        scene: "생활지도",
        text: "아이와 상황에 따라 판단이 달라졌다면, 관찰한 사실과 결정 이유를 나누어 기록해 보세요.",
      },
    ],
    underPressure: [
      {
        scene: "업무",
        text: "바쁠 때 평소보다 한쪽 방식만 반복해서 선택하지 않았는지 살펴볼 수 있어요.",
      },
      {
        scene: "동료",
        text: "상황마다 선택이 달라질 때에는 무엇을 기준으로 바꿨는지 설명하지 않으면 동료가 판단 과정을 알기 어려울 수 있어요.",
      },
    ],
    withColleagues: [
      {
        scene: "동료",
        text: "같은 사람도 회의, 수업 준비, 급한 대응에서 편한 방식이 달라질 수 있음을 대화의 출발점으로 삼아 보세요.",
      },
      {
        scene: "업무",
        text: "이번 일에서 필요한 방식과 다시 판단할 시점을 먼저 맞추면 역할을 나누기 쉬워요.",
      },
    ],
    collaboration: {
      naturalFit: [
        "어느 한쪽 이름에 맞추기보다, 이번 장면에서 자연스러웠던 방식과 그 이유를 나누기 쉬워요.",
        "서로 다른 방식을 사용해 본 경험이 있다면, 각 장면의 조건을 비교해 공통점을 찾아보세요.",
      ],
      needsTuning: [
        "균형 결과가 언제나 중간을 택한다는 뜻은 아니므로, 이번 일에서 선호하는 방식은 따로 말해 두세요.",
        "상황에 따라 방법을 바꿨다면 바꾼 이유와 다시 확인할 시점을 함께 알려 주세요.",
      ],
    },
    nextSteps: [
      "균형으로 나온 관점 하나를 골라, 최근 각 방식을 사용한 장면이 있는지 적어 보세요.",
      "두 장면에서 선택이 달라진 조건을 한 가지씩 표시해 보세요.",
      "다음 비슷한 일이 생기면 무엇을 먼저 확인할지 정해 보세요.",
    ],
    talkingPoints: [
      "같은 일에서도 상황에 따라 다른 방식을 쓴 적이 있나요?",
      "두 방식 중 하나를 더 선호하게 되는 조건은 무엇인가요?",
      "동료에게 내 선택의 이유를 어떻게 설명하나요?",
    ],
  },
  axes: [
    {
      axisId: "axis-energy",
      counterEvidence:
        "최근 한 달이 유난히 바빴거나 함께 일하는 선생님이 바뀌었다면, 평소 모습이 아니라 그 시기의 상황이 답에 실렸을 수 있어요.",
      readings: [
        {
          intensityBandId: "balanced",
          direction: "balanced",
          headline: "이야기와 혼자 정리를 비슷하게 쓰는 편",
          summary: "동료와 이야기하며 정리할 때와 혼자 정리할 때가 비슷하게 나타나요.",
          rhythm: "생각을 정리할 때 동료와 이야기하는 방식과 혼자 정리하는 방식이 비슷하게 나타납니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "positive",
          headline: "두 방식을 쓰되 이야기 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 동료와 이야기하며 정리하는 쪽에 조금 더 가까워요.",
          rhythm: "생각을 정리할 때 두 방식을 함께 쓰되, 동료와 이야기하는 쪽에 조금 더 가깝습니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "negative",
          headline: "두 방식을 쓰되 혼자 정리하는 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 혼자 정리하는 쪽에 조금 더 가까워요.",
          rhythm: "생각을 정리할 때 두 방식을 함께 쓰되, 혼자 정리하는 쪽에 조금 더 가깝습니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "positive",
          headline: "이야기하며 정리한 장면이 있는 편",
          summary: "말로 꺼내 놓고 나면 흩어져 있던 생각이 한 줄로 정리되곤 해요.",
          rhythm: "어떤 장면에서는 동료와 이야기를 나눈 뒤 생각이 정리되는 모습이 나타납니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "negative",
          headline: "혼자 정리한 장면이 있는 편",
          summary: "말을 꺼내기 전에 속으로 한 번 굴려 보고 나면 생각이 또렷해지곤 해요.",
          rhythm: "어떤 장면에서는 혼자 있는 시간을 거친 뒤 생각이 정리되는 모습이 나타납니다.",
        },
        {
          intensityBandId: "clear",
          direction: "positive",
          headline: "여러 장면에서 이야기하며 정리하는 편",
          summary: "머릿속으로만 굴릴 때보다, 누군가에게 설명해 볼 때 결론이 빨리 잡혀요.",
          rhythm: "회의를 비롯한 여러 장면에서 동료와 이야기하며 생각을 정리합니다.",
        },
        {
          intensityBandId: "clear",
          direction: "negative",
          headline: "여러 장면에서 혼자 정리하는 편",
          summary: "여럿이 오간 이야기도 혼자 있는 시간을 거쳐야 내 결론이 돼요.",
          rhythm: "회의를 비롯한 여러 장면에서도 혼자 정리하는 시간을 먼저 둡니다.",
        },
        {
          intensityBandId: "strong",
          direction: "positive",
          headline: "장면이 바뀌어도 이야기하며 정리하는 편",
          summary: "막히는 일이 있으면 혼자 붙들기보다 먼저 이야기할 사람을 찾는 쪽이에요.",
          rhythm: "장면이 바뀌어도 동료와 이야기하며 생각을 정리하는 쪽을 고릅니다.",
        },
        {
          intensityBandId: "strong",
          direction: "negative",
          headline: "장면이 바뀌어도 혼자 정리하는 편",
          summary: "방해받지 않는 시간이 확보돼야 일이 앞으로 나가는 쪽이에요.",
          rhythm: "장면이 바뀌어도 혼자 정리하는 시간을 먼저 마련합니다.",
        },
        {
          intensityBandId: "defining",
          direction: "positive",
          headline: "대부분의 장면에서 이야기하며 정리하는 편",
          summary: "생각이 정리되는 시점이 대체로 말한 뒤라, 대화가 곧 일의 한 과정이에요.",
          rhythm: "혼자 정리할 수 있는 자리에서도 이야기하며 정리하는 쪽을 고르는 모습이 이어집니다.",
        },
        {
          intensityBandId: "defining",
          direction: "negative",
          headline: "대부분의 장면에서 혼자 정리하는 편",
          summary: "생각이 정리되는 시점이 대체로 혼자 있을 때라, 그 시간이 곧 일의 한 과정이에요.",
          rhythm: "여럿이 모인 자리에서도 혼자 정리할 시간을 먼저 마련하는 모습이 이어집니다.",
        },
      ],
    },
    {
      axisId: "axis-lens",
      counterEvidence:
        "올해 맡은 학년이나 교과가 크게 달라졌다면, 평소 보는 방식이 아니라 지금 익히는 중인 방식이 답에 실렸을 수 있어요.",
      readings: [
        {
          intensityBandId: "balanced",
          direction: "balanced",
          headline: "사실과 흐름을 비슷하게 보는 편",
          summary: "관찰한 사실을 살필 때와 앞으로의 흐름을 그릴 때가 비슷하게 나타나요.",
          rhythm: "아이와 수업을 볼 때 관찰한 사실과 앞으로의 흐름을 비슷한 무게로 살핍니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "positive",
          headline: "두 방식을 쓰되 관찰한 사실 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 관찰한 장면과 자료 쪽에 조금 더 가까워요.",
          rhythm: "아이와 수업을 볼 때 두 방식을 함께 쓰되, 관찰한 장면과 자료 쪽에 조금 더 가깝습니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "negative",
          headline: "두 방식을 쓰되 앞으로의 흐름 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 앞으로 이어질 흐름 쪽에 조금 더 가까워요.",
          rhythm: "아이와 수업을 볼 때 두 방식을 함께 쓰되, 앞으로 이어질 흐름 쪽에 조금 더 가깝습니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "positive",
          headline: "관찰한 사실에서 출발한 장면이 있는 편",
          summary: "이야기가 커질 때 실제로 어땠는지를 한 번 짚고 넘어가곤 해요.",
          rhythm: "어떤 장면에서는 관찰한 장면과 자료를 먼저 확인하고 판단합니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "negative",
          headline: "앞으로의 흐름을 먼저 그린 장면이 있는 편",
          summary: "눈앞의 장면을 보면서 이게 어디로 이어질지가 함께 떠오르곤 해요.",
          rhythm: "어떤 장면에서는 앞으로 이어질 흐름을 먼저 그려 보고 판단합니다.",
        },
        {
          intensityBandId: "clear",
          direction: "positive",
          headline: "여러 장면에서 관찰한 사실을 먼저 보는 편",
          summary: "판단이 갈리면 기억보다 남아 있는 기록과 결과물을 먼저 꺼내요.",
          rhythm: "교재 연구와 아이 이해를 비롯한 여러 장면에서 관찰한 사실을 먼저 확인합니다.",
        },
        {
          intensityBandId: "clear",
          direction: "negative",
          headline: "여러 장면에서 앞으로의 흐름을 먼저 보는 편",
          summary: "지금의 모습보다 몇 달 뒤 달라져 있을 모습이 먼저 그려져요.",
          rhythm: "교재 연구와 아이 이해를 비롯한 여러 장면에서 앞으로 이어질 흐름을 먼저 그립니다.",
        },
        {
          intensityBandId: "strong",
          direction: "positive",
          headline: "장면이 바뀌어도 사실에서 출발하는 편",
          summary: "확인되지 않은 전제 위에서는 다음 단계로 잘 넘어가지 않는 쪽이에요.",
          rhythm: "장면이 바뀌어도 확인한 사실에서 출발해 판단을 이어 갑니다.",
        },
        {
          intensityBandId: "strong",
          direction: "negative",
          headline: "장면이 바뀌어도 흐름을 먼저 그리는 편",
          summary: "낱낱의 사실보다 그것들이 만드는 방향이 먼저 눈에 들어오는 쪽이에요.",
          rhythm: "장면이 바뀌어도 앞으로 이어질 흐름을 먼저 그리며 판단을 이어 갑니다.",
        },
        {
          intensityBandId: "defining",
          direction: "positive",
          headline: "대부분의 장면에서 사실을 먼저 보는 편",
          summary: "무엇을 정하든 출발점이 지금 확인된 것이라, 근거가 늘 앞에 놓여요.",
          rhythm: "수업과 아이 이해는 물론 연수 자리까지, 대부분의 장면에서 확인한 사실을 먼저 놓습니다.",
        },
        {
          intensityBandId: "defining",
          direction: "negative",
          headline: "대부분의 장면에서 흐름을 먼저 보는 편",
          summary: "무엇을 보든 그래서 어디로 가는가가 먼저라, 방향이 늘 앞에 놓여요.",
          rhythm: "수업과 아이 이해는 물론 연수 자리까지, 대부분의 장면에서 앞으로 이어질 흐름을 먼저 놓습니다.",
        },
      ],
    },
    {
      axisId: "axis-decision",
      counterEvidence:
        "최근 판단이 어려웠던 일이 하나 크게 남아 있다면, 평소 기준이 아니라 그 일의 기억이 답을 끌어당겼을 수 있어요.",
      readings: [
        {
          intensityBandId: "balanced",
          direction: "balanced",
          headline: "기준과 상황을 비슷하게 살피는 편",
          summary: "정한 기준을 확인할 때와 각자의 상황을 살필 때가 비슷하게 나타나요.",
          rhythm: "결정할 때 정한 기준과 각자가 놓인 상황을 비슷한 무게로 살핍니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "positive",
          headline: "두 방식을 쓰되 기준 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 여럿이 함께 이해할 기준 쪽에 조금 더 가까워요.",
          rhythm: "결정할 때 두 방식을 함께 쓰되, 여럿이 함께 이해할 기준 쪽에 조금 더 가깝습니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "negative",
          headline: "두 방식을 쓰되 상황 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 각자가 놓인 상황 쪽에 조금 더 가까워요.",
          rhythm: "결정할 때 두 방식을 함께 쓰되, 각자가 놓인 상황 쪽에 조금 더 가깝습니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "positive",
          headline: "기준을 먼저 확인한 장면이 있는 편",
          summary: "정하기 전에 무엇을 기준으로 볼지를 한 번 확인하곤 해요.",
          rhythm: "어떤 장면에서는 정해 둔 기준을 먼저 확인하고 결정합니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "negative",
          headline: "상황을 먼저 살핀 장면이 있는 편",
          summary: "정하기 전에 이 사람이 지금 어떤 상황인지가 먼저 걸리곤 해요.",
          rhythm: "어떤 장면에서는 각자가 놓인 상황을 먼저 살피고 결정합니다.",
        },
        {
          intensityBandId: "clear",
          direction: "positive",
          headline: "여러 장면에서 기준을 먼저 확인하는 편",
          summary: "같은 일이 다시 왔을 때 같은 답이 나오는지를 신경 쓰는 편이에요.",
          rhythm: "생활지도와 업무 분담을 비롯한 여러 장면에서 기준을 먼저 확인합니다.",
        },
        {
          intensityBandId: "clear",
          direction: "negative",
          headline: "여러 장면에서 상황을 먼저 살피는 편",
          summary: "같은 규칙도 놓인 형편에 따라 다르게 적용될 수 있다고 보는 편이에요.",
          rhythm: "생활지도와 업무 분담을 비롯한 여러 장면에서 각자의 상황을 먼저 살핍니다.",
        },
        {
          intensityBandId: "strong",
          direction: "positive",
          headline: "장면이 바뀌어도 기준을 앞에 두는 편",
          summary: "남에게 설명할 수 없는 결정은 잘 내리지 않는 쪽이에요.",
          rhythm: "장면이 바뀌어도 여럿에게 설명할 수 있는 기준을 앞에 둡니다.",
        },
        {
          intensityBandId: "strong",
          direction: "negative",
          headline: "장면이 바뀌어도 상황을 앞에 두는 편",
          summary: "사정을 모르는 채로는 결정을 늦추더라도 먼저 들어 보는 쪽이에요.",
          rhythm: "장면이 바뀌어도 각자가 놓인 상황을 앞에 둡니다.",
        },
        {
          intensityBandId: "defining",
          direction: "positive",
          headline: "대부분의 장면에서 기준을 앞에 두는 편",
          summary: "판단의 출발점이 늘 기준이라, 결정보다 기준을 먼저 세워 두는 편이에요.",
          rhythm: "생활지도에서든 업무를 나눌 때든, 대부분의 장면에서 먼저 기준을 놓고 판단합니다.",
        },
        {
          intensityBandId: "defining",
          direction: "negative",
          headline: "대부분의 장면에서 상황을 앞에 두는 편",
          summary: "판단의 출발점이 늘 그 사람의 자리라, 규칙보다 상황을 먼저 읽는 편이에요.",
          rhythm: "생활지도에서든 업무를 나눌 때든, 대부분의 장면에서 먼저 각자의 상황을 살피고 판단합니다.",
        },
      ],
    },
    {
      axisId: "axis-rhythm",
      counterEvidence:
        "학기 초처럼 일정이 몰리는 시기에 답했다면, 평소 리듬이 아니라 그 시기의 업무량이 답에 실렸을 수 있어요.",
      readings: [
        {
          intensityBandId: "balanced",
          direction: "balanced",
          headline: "계획과 조정을 비슷하게 쓰는 편",
          summary: "미리 정해 두고 시작할 때와 현장에서 조정할 때가 비슷하게 나타나요.",
          rhythm: "일을 이어 갈 때 미리 정해 두는 방식과 현장에서 조정하는 방식이 비슷하게 나타납니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "positive",
          headline: "두 방식을 쓰되 미리 정해 두는 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 순서를 미리 정해 두는 쪽에 조금 더 가까워요.",
          rhythm: "일을 이어 갈 때 두 방식을 함께 쓰되, 순서를 미리 정해 두는 쪽에 조금 더 가깝습니다.",
        },
        {
          intensityBandId: "balanced",
          direction: "negative",
          headline: "두 방식을 쓰되 현장에서 조정하는 쪽에 조금 가까운 편",
          summary: "두 방식을 함께 쓰지만, 현장에서 방법을 조정하는 쪽에 조금 더 가까워요.",
          rhythm: "일을 이어 갈 때 두 방식을 함께 쓰되, 현장에서 방법을 조정하는 쪽에 조금 더 가깝습니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "positive",
          headline: "미리 정해 두고 시작한 장면이 있는 편",
          summary: "시작하기 전에 순서를 한 번 훑어 두면 마음이 놓이곤 해요.",
          rhythm: "어떤 장면에서는 순서와 준비를 미리 정해 두고 시작합니다.",
        },
        {
          intensityBandId: "leaning",
          direction: "negative",
          headline: "현장에서 조정한 장면이 있는 편",
          summary: "해 보면서 더 나은 방법이 보이면 그쪽으로 바꾸곤 해요.",
          rhythm: "어떤 장면에서는 큰 방향만 두고 현장에서 방법을 조정합니다.",
        },
        {
          intensityBandId: "clear",
          direction: "positive",
          headline: "여러 장면에서 미리 정해 두는 편",
          summary: "무엇을 언제 할지가 보이면 그때부터 속도가 붙는 편이에요.",
          rhythm: "수업 준비와 업무를 비롯한 여러 장면에서 순서를 미리 정해 두고 시작합니다.",
        },
        {
          intensityBandId: "clear",
          direction: "negative",
          headline: "여러 장면에서 현장에 맞춰 조정하는 편",
          summary: "정해 둔 대로보다 그날 상황에 맞는 쪽을 고르는 편이에요.",
          rhythm: "수업 준비와 업무를 비롯한 여러 장면에서 현장 상황에 맞춰 방법을 조정합니다.",
        },
        {
          intensityBandId: "strong",
          direction: "positive",
          headline: "장면이 바뀌어도 미리 정해 두는 편",
          summary: "준비가 덜 된 채 출발하는 것을 잘 견디지 않는 쪽이에요.",
          rhythm: "장면이 바뀌어도 순서와 준비를 먼저 정한 뒤 움직입니다.",
        },
        {
          intensityBandId: "strong",
          direction: "negative",
          headline: "장면이 바뀌어도 현장에 맞춰 조정하는 편",
          summary: "흐름이 어긋나도 크게 흔들리지 않고 다음 수를 찾는 쪽이에요.",
          rhythm: "장면이 바뀌어도 큰 방향을 두고 현장에서 방법을 맞춰 갑니다.",
        },
        {
          intensityBandId: "defining",
          direction: "positive",
          headline: "대부분의 장면에서 미리 정해 두는 편",
          summary: "일이 시작되는 시점이 대체로 순서가 정해진 뒤예요.",
          rhythm: "수업과 업무는 물론 하루를 여는 자리까지, 대부분의 장면에서 순서를 먼저 정해 둡니다.",
        },
        {
          intensityBandId: "defining",
          direction: "negative",
          headline: "대부분의 장면에서 현장에 맞춰 조정하는 편",
          summary: "방법이 정해지는 시점이 대체로 해 보는 중이에요.",
          rhythm: "수업과 업무는 물론 하루를 여는 자리까지, 대부분의 장면에서 그때 상황에 맞춰 방법을 조정합니다.",
        },
      ],
    },
  ],
} as const;
